-- ============================================
-- Quattre Istambul - Atualização de Status
-- Execute este script no SQL Editor do Supabase
-- Atualiza APENAS status, preservando todos os demais campos (incluindo preço)
-- Valores válidos: 'disponivel', 'reservado', 'vendido'
-- ============================================

UPDATE units SET status = 'disponivel' WHERE unidade = 101;
UPDATE units SET status = 'disponivel' WHERE unidade = 102;
UPDATE units SET status = 'disponivel' WHERE unidade = 103;
UPDATE units SET status = 'disponivel' WHERE unidade = 104;
UPDATE units SET status = 'disponivel' WHERE unidade = 105;
UPDATE units SET status = 'disponivel' WHERE unidade = 106;
UPDATE units SET status = 'disponivel' WHERE unidade = 107;
UPDATE units SET status = 'disponivel' WHERE unidade = 108;
UPDATE units SET status = 'disponivel' WHERE unidade = 109;
UPDATE units SET status = 'disponivel' WHERE unidade = 110;
UPDATE units SET status = 'disponivel' WHERE unidade = 111;
UPDATE units SET status = 'disponivel' WHERE unidade = 112;
UPDATE units SET status = 'disponivel' WHERE unidade = 201;
UPDATE units SET status = 'disponivel' WHERE unidade = 202;
UPDATE units SET status = 'disponivel' WHERE unidade = 203;
UPDATE units SET status = 'disponivel' WHERE unidade = 204;
UPDATE units SET status = 'disponivel' WHERE unidade = 205;
UPDATE units SET status = 'disponivel' WHERE unidade = 206;
UPDATE units SET status = 'disponivel' WHERE unidade = 207;
UPDATE units SET status = 'disponivel' WHERE unidade = 208;
UPDATE units SET status = 'disponivel' WHERE unidade = 209;
UPDATE units SET status = 'disponivel' WHERE unidade = 210;
UPDATE units SET status = 'disponivel' WHERE unidade = 211;
UPDATE units SET status = 'disponivel' WHERE unidade = 212;
UPDATE units SET status = 'disponivel' WHERE unidade = 301;
UPDATE units SET status = 'disponivel' WHERE unidade = 302;
UPDATE units SET status = 'disponivel' WHERE unidade = 303;
UPDATE units SET status = 'disponivel' WHERE unidade = 304;
UPDATE units SET status = 'disponivel' WHERE unidade = 305;
UPDATE units SET status = 'disponivel' WHERE unidade = 306;
UPDATE units SET status = 'disponivel' WHERE unidade = 307;
UPDATE units SET status = 'disponivel' WHERE unidade = 308;
UPDATE units SET status = 'disponivel' WHERE unidade = 309;
UPDATE units SET status = 'disponivel' WHERE unidade = 310;
UPDATE units SET status = 'disponivel' WHERE unidade = 311;
UPDATE units SET status = 'disponivel' WHERE unidade = 312;
UPDATE units SET status = 'disponivel' WHERE unidade = 401;
UPDATE units SET status = 'disponivel' WHERE unidade = 402;
UPDATE units SET status = 'disponivel' WHERE unidade = 403;
UPDATE units SET status = 'disponivel' WHERE unidade = 404;
UPDATE units SET status = 'disponivel' WHERE unidade = 405;
UPDATE units SET status = 'disponivel' WHERE unidade = 406;
UPDATE units SET status = 'disponivel' WHERE unidade = 407;
UPDATE units SET status = 'disponivel' WHERE unidade = 408;
UPDATE units SET status = 'disponivel' WHERE unidade = 409;
UPDATE units SET status = 'disponivel' WHERE unidade = 410;
UPDATE units SET status = 'disponivel' WHERE unidade = 411;
UPDATE units SET status = 'disponivel' WHERE unidade = 412;
UPDATE units SET status = 'disponivel' WHERE unidade = 501;
UPDATE units SET status = 'disponivel' WHERE unidade = 502;
UPDATE units SET status = 'disponivel' WHERE unidade = 503;
UPDATE units SET status = 'disponivel' WHERE unidade = 504;
UPDATE units SET status = 'disponivel' WHERE unidade = 505;
UPDATE units SET status = 'disponivel' WHERE unidade = 506;
UPDATE units SET status = 'disponivel' WHERE unidade = 507;
UPDATE units SET status = 'disponivel' WHERE unidade = 508;
UPDATE units SET status = 'disponivel' WHERE unidade = 509;
UPDATE units SET status = 'disponivel' WHERE unidade = 510;
UPDATE units SET status = 'disponivel' WHERE unidade = 511;
UPDATE units SET status = 'disponivel' WHERE unidade = 512;
UPDATE units SET status = 'disponivel' WHERE unidade = 601;
UPDATE units SET status = 'disponivel' WHERE unidade = 602;
UPDATE units SET status = 'disponivel' WHERE unidade = 603;
UPDATE units SET status = 'disponivel' WHERE unidade = 604;
UPDATE units SET status = 'disponivel' WHERE unidade = 605;
UPDATE units SET status = 'disponivel' WHERE unidade = 606;
UPDATE units SET status = 'disponivel' WHERE unidade = 607;
UPDATE units SET status = 'disponivel' WHERE unidade = 608;
UPDATE units SET status = 'disponivel' WHERE unidade = 609;
UPDATE units SET status = 'disponivel' WHERE unidade = 610;
UPDATE units SET status = 'disponivel' WHERE unidade = 611;
UPDATE units SET status = 'disponivel' WHERE unidade = 612;
