import re

text = open('scripts/imobsync_proposal/proposta_imobsync.html', 'r').read()

replacements = [
    ('Gestao', 'Gestão'),
    ('Sincronizacao', 'Sincronização'),
    ('sincronizacao', 'sincronização'),
    ('informacao', 'informação'),
    ('operacao', 'operação'),
    ('condicoes', 'condições'),
    ('simulacao', 'simulação'),
    ('atualizacao', 'atualização'),
    ('organizacao', 'organização'),
    ('implantacao', 'implantação'),
    ('orientacao', 'orientação'),
    ('utilizacao', 'utilização'),
    ('eficiencia', 'eficiência'),
    ('dependencia', 'dependência'),
    ('desatualizada', 'desatualizada'),
    ('unica', 'única'),
    ('esta', 'está'),
    ('incluido', 'incluído'),
    ('Contemplado', 'Contemplado'),
    ('Beneficios', 'Benefícios'),
    ('Autonomo', 'Autônomo'),
    ('relacionado', 'relacionado'),
    ('manutencao', 'manutenção'),
    ('disponibilizacao', 'disponibilização'),
    ('Prontos para sincronizar a operacao comercial', 'Prontos para sincronizar a operação comercial'),
    ('equipe comercial', 'equipe comercial'),
    ('multiplas', 'múltiplas'),
    ('múltiplos', 'múltiplos'),
    ('não são', 'não são'),
    ('é comum', 'é comum'),
    ('estão', 'estão'),
    ('têm', 'têm'),
    ('também', 'também'),
    ('será', 'será'),
    ('já', 'já'),
    ('não', 'não'),
    ('você', 'você'),
    ('está', 'está'),
    ('público', 'público'),
    ('próximo', 'próximo'),
    ('próximos', 'próximos'),
    ('diretrizes', 'diretrizes'),
    ('corretor', 'corretor'),
    ('corretores', 'corretores'),
    ('coordenador', 'coordenador'),
    ('coordenadores', 'coordenadores'),
    ('empreendimento', 'empreendimento'),
    ('empreendimentos', 'empreendimentos'),
    ('imobiliária', 'imobiliária'),
    ('imobiliarias', 'imobiliárias'),
    ('simulador', 'simulador'),
    ('calculos', 'cálculos'),
    ('necessário', 'necessário'),
    ('necessária', 'necessária'),
    ('específica', 'específica'),
    ('rápido', 'rápido'),
    ('rápida', 'rápida'),
    ('prática', 'prática'),
    ('fácil', 'fácil'),
    ('fácil', 'fácil'),
    ('útil', 'útil'),
    ('área', 'área'),
    ('sobre', 'sobre'),
    ('possível', 'possível'),
    ('dispersão', 'dispersão'),
    ('informações', 'informações'),
    ('operação', 'operação'),
    ('conexão', 'conexão'),
    ('proteção', 'proteção'),
    ('correção', 'correção'),
    ('atualização', 'atualização'),
    ('disponibilidade', 'disponibilidade'),
    ('construtora', 'construtora'),
    ('construtoras', 'construtoras'),
    ('financiamento', 'financiamento'),
    ('simulação', 'simulação'),
    ('estimativa', 'estimativa'),
    ('gestão', 'gestão'),
    ('quantidade', 'quantidade'),
    ('verificação', 'verificação'),
    ('confiável', 'confiável'),
    ('profissional', 'profissional'),
    ('tecnologia', 'tecnologia'),
    ('experiência', 'experiência'),
    ('estrutura', 'estrutura'),
    ('operação', 'operação'),
    ('desenvolvimento', 'desenvolvimento'),
    ('personalizada', 'personalizada'),
    ('visualmente', 'visualmente'),
    ('persuasiva', 'persuasiva'),
    ('condição', 'condição'),
    ('condições', 'condições'),
    ('situação', 'situação'),
    ('importância', 'importância'),
    ('integração', 'integração'),
    ('representação', 'representação'),
    ('autonomia', 'autonomia'),
    ('qualidade', 'qualidade'),
    ('disponibilização', 'disponibilização'),
    ('manutenção', 'manutenção'),
    ('exatidão', 'exatidão'),
    ('precisão', 'precisão'),
    ('ferramenta', 'ferramenta'),
    ('plataforma', 'plataforma'),
    ('funcionamento', 'funcionamento'),
    ('contratação', 'contratação'),
    ('vantajosa', 'vantajosa'),
    ('econômica', 'econômica'),
    ('flexível', 'flexível'),
    ('igual', 'igual'),
    ('período', 'período'),
    ('anual', 'anual'),
    ('mensal', 'mensal'),
    ('semanal', 'semanal'),
    ('diário', 'diário'),
    ('horário', 'horário'),
    ('contratual', 'contratual'),
    ('complexidade', 'complexidade'),
    ('dinâmica', 'dinâmica'),
    ('frequência', 'frequência'),
    ('reais', 'reais'),
    ('reais', 'reais'),
    ('atualizados', 'atualizados'),
    ('atualizadas', 'atualizadas'),
    ('gerenciamento', 'gerenciamento'),
    ('acessíveis', 'acessíveis'),
    ('consultem', 'consultem'),
    ('realizem', 'realizem'),
    ('possam', 'possam'),
    ('devem', 'devem'),
    ('terão', 'terão'),
    ('terá', 'terá'),
    ('poderão', 'poderão'),
    ('pode', 'pode'),
    ('pôr', 'pôr'),
    ('através', 'através'),
    ('até', 'até'),
    ('também', 'também'),
    ('são', 'são'),
    ('estão', 'estão'),
    ('será', 'será'),
    ('serão', 'serão'),
    ('tinha', 'tinha'),
    ('havia', 'havia'),
    ('teria', 'teria'),
    ('faria', 'faria'),
    ('poderia', 'poderia'),
    ('deveria', 'deveria'),
    ('gostaria', 'gostaria'),
    ('gostaria', 'gostaria'),
]

# Simple approach: replace unaccented words with accented versions
# in Portuguese context
simple = {
    'Gestao': 'Gestão', 'Sincronizacao': 'Sincronização',
    'informacao': 'informação', 'operacao': 'operação',
    'condicoes': 'condições', 'simulacao': 'simulação',
    'atualizacao': 'atualização', 'organizacao': 'organização',
    'implantacao': 'implantação', 'orientacao': 'orientação',
    'utilizacao': 'utilização', 'eficiencia': 'eficiência',
    'dependencia': 'dependência', 'unica': 'única',
    'esta ': 'está ', 'incluido': 'incluído',
    'Beneficios': 'Benefícios',
    'manutencao': 'manutenção',
    'disponibilizacao': 'disponibilização',
}

for old, new in simple.items():
    text = text.replace(old, new)

# Fix specific phrases
phrases = [
    ('sincronizar a operacao comercial', 'sincronizar a operação comercial'),
    ('informacao esta dispersa', 'informação está dispersa'),
    ('operacao perde velocidade', 'operação perde velocidade'),
    ('unica fonte para a informacao', 'única fonte para a informação'),
    ('um fluxo simples, uma operacao conectada', 'um fluxo simples, uma operação conectada'),
    ('condicoes comerciais em uma simulacao clara', 'condições comerciais em uma simulação clara'),
    ('Mais eficiencia para coordenadores', 'Mais eficiência para coordenadores'),
    ('Implantacao simples, acompanhada de perto', 'Implantação simples, acompanhada de perto'),
    ('O que esta incluido', 'O que está incluído'),
    ('Condicoes comerciais para implantacao', 'Condições comerciais para implantação'),
    ('Uma unica plataforma', 'Uma única plataforma'),
    ('Implantacao e Suporte', 'Implantação e Suporte'),
    ('O Que Esta Contemplado', 'O Que Está Contemplado'),
    ('relacionado a utilizacao', 'relacionado à utilização'),
    ('Plataforma de Gestao e Sincronizacao', 'Plataforma de Gestão e Sincronização'),
]

for old, new in phrases:
    text = text.replace(old, new)

open('scripts/imobsync_proposal/proposta_imobsync.html', 'w').write(text)
print('Done - accents fixed')
